---
title: "How to: install"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{How to: install}
  %\VignetteEngine{knitr::knitr}
  \usepackage[utf8]{inputenc}
---



```{r include = FALSE}
library(Eagle)
```

## How to install Eagle

1. Can install Eagle_1.0.0.tar.gz using R CMD INSTALL Eagle_1.0.0.tar.gz
   but need to install dependent packages Rcpp RcppEigen shiny first. 
2. Go into R. 
   use install.packages("Eagle_1.0.0.tar.gz", repos=NULL)   
   but you also have to install dependent packages first. 
3. From CRAN, you can use 
   install.packages("Eagle", dependencies=TRUE)  and this will install all dependent packages 
   as well as Eagle. 

process on VM - ubuntu
went into R session
Q I'm running as sudo, does this matter?
install.packages("Rcpp")  -- asked for repository
install.packages("RcppEigen")
install.packages("shiny")

then typed
install.packages("Eagle_1.0.0.0.tar.gz", repos=NULL)





Notes - Ubuntu 
29/03/17
R CMD INSTALL Eagle_1.0.0.tar.gz on virgin R system failed due to dependencies 
   Rcpp, RcppEigen, shiny, matrixcal, shinythemes

Now failing due to mkl.h not being found
 - I've changed ./build pipeline to remove mention of mkl by removing Makevars.gpu
 - also changed ./build to remove memtion in RcppFuction via commenting out 
   define EIGEN_USE_MKL_ALL " > ./tmp1
 WARNING EGEIN will no longer do impicit parallezation (I think) 

Issue:
    getting core dump for ReadMarker - could it be memory map code?
Solution
this was causing a seg fault
char outputBuffer[bufferSize];

but this is good
 char* outputBuffer = NULL;
outputBuffer = new char[bufferSize];



## how to generate html code 

1. module load pandoc
2. export RSTUDIO_PANDOC=$PANDOC_HOME
3. R
4. load(rmarkdown)
5. run render("QuickStart.Rmd")   ## this allows you to use different style themes. 




