# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

checkGenotypes <- function(f_name) {
    invisible(.Call('WMAM_checkGenotypes', PACKAGE = 'WMAM', f_name))
}

getRowColumn <- function(fname) {
    .Call('WMAM_getRowColumn', PACKAGE = 'WMAM', fname)
}

createMt_rcpp <- function(f_name, f_name_bin, max_memory_in_Gbytes, dims) {
    invisible(.Call('WMAM_createMt_rcpp', PACKAGE = 'WMAM', f_name, f_name_bin, max_memory_in_Gbytes, dims))
}

calculate_reduced_a_rcpp <- function(f_name_bin, varG, P, y, max_memory_in_Gbytes, dims, selected_loci) {
    .Call('WMAM_calculate_reduced_a_rcpp', PACKAGE = 'WMAM', f_name_bin, varG, P, y, max_memory_in_Gbytes, dims, selected_loci)
}

calculate_a_and_vara_rcpp <- function(f_name_bin, selected_loci, inv_MMt_sqrt, dim_reduced_vara, max_memory_in_Gbytes, dims, a) {
    .Call('WMAM_calculate_a_and_vara_rcpp', PACKAGE = 'WMAM', f_name_bin, selected_loci, inv_MMt_sqrt, dim_reduced_vara, max_memory_in_Gbytes, dims, a)
}

createM_rcpp <- function(f_name, f_name_bin, max_memory_in_Gbytes, dims) {
    invisible(.Call('WMAM_createM_rcpp', PACKAGE = 'WMAM', f_name, f_name_bin, max_memory_in_Gbytes, dims))
}

extract_geno_rcpp <- function(f_name_bin, max_memory_in_Gbytes, selected_locus, dims) {
    .Call('WMAM_extract_geno_rcpp', PACKAGE = 'WMAM', f_name_bin, max_memory_in_Gbytes, selected_locus, dims)
}

calculateMMt_rcpp <- function(f_name_bin, max_memory_in_Gbytes, num_cores, selected_loci, dims) {
    .Call('WMAM_calculateMMt_rcpp', PACKAGE = 'WMAM', f_name_bin, max_memory_in_Gbytes, num_cores, selected_loci, dims)
}

